<a href="https://colab.research.google.com/github/Ritesh-panda/datascience-learnings/blob/main/Logistics_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
from sklearn.linear_model import LogisticRegression

In [19]:
df = {
    'Age': [22, 25, 18, 45, 12, 43, 23, 33],
    'Gender': ['F', 'F', 'M', 'M', 'F', 'M', 'M', 'M'],
    'Smoker': ['N', 'S', 'S', 'N', 'S', 'S', 'S', 'S'],
    'Disease': [1, 1, 0, 0, 0, 1, 0, 1]
}

In [20]:
df

{'Age': [22, 25, 18, 45, 12, 43, 23, 33],
 'Gender': ['F', 'F', 'M', 'M', 'F', 'M', 'M', 'M'],
 'Smoker': ['N', 'S', 'S', 'N', 'S', 'S', 'S', 'S'],
 'Disease': [1, 1, 0, 0, 0, 1, 0, 1]}

In [27]:
df = pd.DataFrame(data)
df = pd.get_dummies(df, columns=['Gender','Smoker'])

In [28]:
df.head()

   Age  Disease  Gender_F  Gender_M  Smoker_N  Smoker_S
0   22        1      True     False      True     False
1   25        1      True     False     False      True
2   18        0     False      True     False      True
3   45        0     False      True      True     False
4   12        0      True     False     False      True

In [29]:
for col in ['Gender_F', 'Gender_M', 'Smoker_N', 'Smoker_S']:
    df[col] = df[col].astype(int)

display(df.head())

   Age  Disease  Gender_F  Gender_M  Smoker_N  Smoker_S
0   22        1         1         0         1         0
1   25        1         1         0         0         1
2   18        0         0         1         0         1
3   45        0         0         1         1         0
4   12        0         1         0         0         1

In [32]:
#separate the feature x and target var y
x=df.drop(columns='Disease', axis=1)
y=df['Disease']

In [34]:
model=LogisticRegression()
model

LogisticRegression()

In [38]:
from IPython.core import interactiveshell
model.fit(x, y)
#get the regression coeeficient and the intercept
coef=model.coef_[0]
intercept=model.intercept_[0]

In [40]:
print('Regression Coefficients (m1,m2,m3,m4,m5):',coef)

Regression Coefficients (m1,m2,m3,m4,m5): [ 0.08564059  0.53338973 -0.53349833 -0.17495214  0.17484355]